"""empty message

Revision ID: 06aa278f0dcf
Revises: ed4a59a479eb
Create Date: 2022-06-10 12:15:22.353393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06aa278f0dcf'
down_revision = 'ed4a59a479eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_payment_id_payment', type_='foreignkey')
        batch_op.drop_column('payment_id')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_payment_order_id_order'), 'order', ['order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payment_order_id_order'), type_='foreignkey')
        batch_op.drop_column('order_id')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_order_payment_id_payment', 'payment', ['payment_id'], ['id'])

    op.create_table('order_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('product', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('total', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='fk_order_item_order_id_order'),
    sa.ForeignKeyConstraint(['product'], ['products.id'], name='fk_order_item_product_products'),
    sa.PrimaryKeyConstraint('id', name='pk_order_item')
    )
    # ### end Alembic commands ###
