"""empty message

Revision ID: 0a0ce7feb911
Revises: 58f9c829be7f
Create Date: 2022-05-26 11:50:12.097106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0ce7feb911'
down_revision = '58f9c829be7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cart_item_productid_products', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_cart_item_productid_products'), 'products', ['productid'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('paid')

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cart_item_productid_products'), type_='foreignkey')
        batch_op.create_foreign_key('fk_cart_item_productid_products', 'products', ['productid'], ['id'])

    # ### end Alembic commands ###
