"""empty message

Revision ID: 0f6716244a6a
Revises: 56927ad64c17
Create Date: 2022-07-12 13:20:52.687867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6716244a6a'
down_revision = '56927ad64c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('delivery_address', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('contact', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('comments', sa.String(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_confirmed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('comments')
        batch_op.drop_column('contact')
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
