"""empty message

Revision ID: 6bca68035713
Revises: d3701eb74111
Create Date: 2022-05-30 11:11:59.300856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bca68035713'
down_revision = 'd3701eb74111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_order')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_payment_id_payment', type_='foreignkey')
        batch_op.drop_column('payment_id')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_payment_order_id_order'), 'order', ['order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payment_order_id_order'), type_='foreignkey')
        batch_op.drop_column('order_id')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_order_payment_id_payment', 'payment', ['payment_id'], ['id'])

    op.create_table('_alembic_tmp_order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_number', sa.INTEGER(), nullable=False),
    sa.Column('order_date', sa.DATETIME(), nullable=False),
    sa.Column('total_price', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('paid', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_order_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_order'),
    sa.UniqueConstraint('order_number', name='uq_order_order_number')
    )
    # ### end Alembic commands ###
